OBJLIB?=ANGO1

QOBJLIB=/QSYS.LIB/$(OBJLIB).LIB
# QSRC_PATH=/home/ANGO/CPYSCN2SVG

all: $(QOBJLIB)/CPYSCN2SVG.CMD $(QOBJLIB)/CPYSCN2SVG.PGM

$(QOBJLIB)/CPYSCN2SVG.CMD: QCMDSRC/CPYSCN2SVG.CMD
	system "CRTCMD CMD($(OBJLIB)/CPYSCN2SVG) PGM($(OBJLIB)/CPYSCN2SVG) SRCSTMF('QCMDSRC/CPYSCN2SVG.CMD') PRDLIB($(OBJLIB))"

$(QOBJLIB)/CPYSCN2SVG.PGM: QRPGLESRC/CPYSCN2SVG.SQLRPGLE
# to avoid RNF0733 "The record length of the output file is too small."
	system "CRTSRCPF QTEMP/QSQLPRE RCDLEN(112)"
	system "CRTSQLRPGI OBJ($(OBJLIB)/CPYSCN2SVG) SRCSTMF('QRPGLESRC/CPYSCN2SVG.SQLRPGLE') INCDIR('./') RPGPPOPT(*LVL2) COMPILEOPT('TGTCCSID(*JOB)') DBGVIEW(*LIST)"
